version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak-web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

    entrypoint: [ "/opt/keycloak/keycloak-init.sh" ]
    volumes:
      - ./shopping-realm.json:/opt/keycloak/shopping-realm.json
      - ./shopping-realm-users-0.json:/opt/keycloak/shopping-realm-users-0.json
      - ./shopping-realm-users-1.json:/opt/keycloak/shopping-realm-users-1.json
      - ./keycloak-init.sh:/opt/keycloak/keycloak-init.sh
      - ./keycloak:/opt/keycloak/data
      - ./themes:/opt/keycloak/providers/
    ports:
      - "8090:8080"
    depends_on:
      - keycloak-db
    networks:
      - shopping-list-network

  keycloak-db:
    image: postgres:latest
    container_name: keycloak-db
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - ./keycloak-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - shopping-list-network

  postgres:
    image: postgres:latest
    container_name: shopping-list-db
    environment:
      POSTGRES_DB: shopping
      POSTGRES_USER: shopping
      POSTGRES_PASSWORD: shopping
    volumes:
      - ./shopping-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shopping-list-network

networks:
  shopping-list-network:
    driver: bridge

volumes:
  keycloak-db:
    driver: local
  shopping-db:
    driver: local
